image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  only: master
  script:
    - npm install
    - npm run jsdoc
    - mkdir .public
    - cp -r docs/* .public
    - mv .public public
  artifacts:
    paths:
    - public